// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type ExprStatus string

const (
	ExprStatusPending    ExprStatus = "pending"
	ExprStatusInProgress ExprStatus = "in_progress"
	ExprStatusDone       ExprStatus = "done"
	ExprStatusFailed     ExprStatus = "failed"
)

func (e *ExprStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExprStatus(s)
	case string:
		*e = ExprStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ExprStatus: %T", src)
	}
	return nil
}

type NullExprStatus struct {
	ExprStatus ExprStatus `json:"expr_status"`
	Valid      bool       `json:"valid"` // Valid is true if ExprStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExprStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ExprStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExprStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExprStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExprStatus), nil
}

type TaskStatus string

const (
	TaskStatusPending TaskStatus = "pending"
	TaskStatusReady   TaskStatus = "ready"
	TaskStatusRunning TaskStatus = "running"
	TaskStatusDone    TaskStatus = "done"
	TaskStatusFailed  TaskStatus = "failed"
)

func (e *TaskStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskStatus(s)
	case string:
		*e = TaskStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskStatus: %T", src)
	}
	return nil
}

type NullTaskStatus struct {
	TaskStatus TaskStatus `json:"task_status"`
	Valid      bool       `json:"valid"` // Valid is true if TaskStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TaskStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskStatus), nil
}

type Expression struct {
	ID        uuid.UUID  `json:"id"`
	Raw       string     `json:"raw"`
	Status    ExprStatus `json:"status"`
	Result    *float64   `json:"result"`
	Error     *string    `json:"error"`
	TraceID   string     `json:"trace_id"`
	CreatedAt time.Time  `json:"created_at"`
	DoneAt    *time.Time `json:"done_at"`
}

type Outbox struct {
	ID          int64      `json:"id"`
	Kind        string     `json:"kind"`
	Payload     []byte     `json:"payload"`
	CreatedAt   time.Time  `json:"created_at"`
	PublishedAt *time.Time `json:"published_at"`
}

type Task struct {
	ID           uuid.UUID  `json:"id"`
	ExpressionID uuid.UUID  `json:"expression_id"`
	Op           string     `json:"op"`
	Arg1Value    *float64   `json:"arg1_value"`
	Arg1TaskID   *uuid.UUID `json:"arg1_task_id"`
	Arg2Value    *float64   `json:"arg2_value"`
	Arg2TaskID   *uuid.UUID `json:"arg2_task_id"`
	UnmetDeps    int32      `json:"unmet_deps"`
	Status       TaskStatus `json:"status"`
	Result       *float64   `json:"result"`
	Attempt      int32      `json:"attempt"`
	WorkerID     string     `json:"worker_id"`
	IsRoot       bool       `json:"is_root"`
	QueuedAt     *time.Time `json:"queued_at"`
	StartedAt    *time.Time `json:"started_at"`
	FinishedAt   *time.Time `json:"finished_at"`
}
