// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const bumpTaskAttempt = `-- name: BumpTaskAttempt :one
UPDATE tasks SET attempt = attempt + 1 WHERE id = $1 RETURNING attempt
`

func (q *Queries) BumpTaskAttempt(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, bumpTaskAttempt, id)
	var attempt int32
	err := row.Scan(&attempt)
	return attempt, err
}

const completeTask = `-- name: CompleteTask :one
UPDATE tasks
SET status = 'done', result = $2, finished_at = now()
WHERE id = $1 AND status NOT IN ('done', 'failed')
RETURNING id, expression_id, is_root
`

type CompleteTaskParams struct {
	ID     uuid.UUID `json:"id"`
	Result *float64  `json:"result"`
}

type CompleteTaskRow struct {
	ID           uuid.UUID `json:"id"`
	ExpressionID uuid.UUID `json:"expression_id"`
	IsRoot       bool      `json:"is_root"`
}

// Idempotent: only transitions once; a duplicate result finds no row.
func (q *Queries) CompleteTask(ctx context.Context, arg CompleteTaskParams) (CompleteTaskRow, error) {
	row := q.db.QueryRow(ctx, completeTask, arg.ID, arg.Result)
	var i CompleteTaskRow
	err := row.Scan(&i.ID, &i.ExpressionID, &i.IsRoot)
	return i, err
}

const failTask = `-- name: FailTask :one
UPDATE tasks
SET status = 'failed', finished_at = now()
WHERE id = $1 AND status NOT IN ('done', 'failed')
RETURNING id, expression_id, is_root
`

type FailTaskRow struct {
	ID           uuid.UUID `json:"id"`
	ExpressionID uuid.UUID `json:"expression_id"`
	IsRoot       bool      `json:"is_root"`
}

func (q *Queries) FailTask(ctx context.Context, id uuid.UUID) (FailTaskRow, error) {
	row := q.db.QueryRow(ctx, failTask, id)
	var i FailTaskRow
	err := row.Scan(&i.ID, &i.ExpressionID, &i.IsRoot)
	return i, err
}

const fillArg1FromResult = `-- name: FillArg1FromResult :many
UPDATE tasks
SET arg1_value = $2, unmet_deps = unmet_deps - 1
WHERE arg1_task_id = $1 AND status = 'pending'
RETURNING id, op, arg1_value, arg2_value, unmet_deps
`

type FillArg1FromResultParams struct {
	Arg1TaskID *uuid.UUID `json:"arg1_task_id"`
	Arg1Value  *float64   `json:"arg1_value"`
}

type FillArg1FromResultRow struct {
	ID        uuid.UUID `json:"id"`
	Op        string    `json:"op"`
	Arg1Value *float64  `json:"arg1_value"`
	Arg2Value *float64  `json:"arg2_value"`
	UnmetDeps int32     `json:"unmet_deps"`
}

// Fan-in: propagate a finished task's result into dependents' first argument.
func (q *Queries) FillArg1FromResult(ctx context.Context, arg FillArg1FromResultParams) ([]FillArg1FromResultRow, error) {
	rows, err := q.db.Query(ctx, fillArg1FromResult, arg.Arg1TaskID, arg.Arg1Value)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FillArg1FromResultRow
	for rows.Next() {
		var i FillArg1FromResultRow
		if err := rows.Scan(
			&i.ID,
			&i.Op,
			&i.Arg1Value,
			&i.Arg2Value,
			&i.UnmetDeps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fillArg2FromResult = `-- name: FillArg2FromResult :many
UPDATE tasks
SET arg2_value = $2, unmet_deps = unmet_deps - 1
WHERE arg2_task_id = $1 AND status = 'pending'
RETURNING id, op, arg1_value, arg2_value, unmet_deps
`

type FillArg2FromResultParams struct {
	Arg2TaskID *uuid.UUID `json:"arg2_task_id"`
	Arg2Value  *float64   `json:"arg2_value"`
}

type FillArg2FromResultRow struct {
	ID        uuid.UUID `json:"id"`
	Op        string    `json:"op"`
	Arg1Value *float64  `json:"arg1_value"`
	Arg2Value *float64  `json:"arg2_value"`
	UnmetDeps int32     `json:"unmet_deps"`
}

func (q *Queries) FillArg2FromResult(ctx context.Context, arg FillArg2FromResultParams) ([]FillArg2FromResultRow, error) {
	rows, err := q.db.Query(ctx, fillArg2FromResult, arg.Arg2TaskID, arg.Arg2Value)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FillArg2FromResultRow
	for rows.Next() {
		var i FillArg2FromResultRow
		if err := rows.Scan(
			&i.ID,
			&i.Op,
			&i.Arg1Value,
			&i.Arg2Value,
			&i.UnmetDeps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasksByExpression = `-- name: GetTasksByExpression :many
SELECT id, expression_id, op, arg1_value, arg1_task_id, arg2_value, arg2_task_id, unmet_deps, status, result, attempt, worker_id, is_root, queued_at, started_at, finished_at FROM tasks WHERE expression_id = $1 ORDER BY id
`

func (q *Queries) GetTasksByExpression(ctx context.Context, expressionID uuid.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTasksByExpression, expressionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ExpressionID,
			&i.Op,
			&i.Arg1Value,
			&i.Arg1TaskID,
			&i.Arg2Value,
			&i.Arg2TaskID,
			&i.UnmetDeps,
			&i.Status,
			&i.Result,
			&i.Attempt,
			&i.WorkerID,
			&i.IsRoot,
			&i.QueuedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTask = `-- name: InsertTask :exec
INSERT INTO tasks (
    id, expression_id, op,
    arg1_value, arg1_task_id, arg2_value, arg2_task_id,
    unmet_deps, status, is_root
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertTaskParams struct {
	ID           uuid.UUID  `json:"id"`
	ExpressionID uuid.UUID  `json:"expression_id"`
	Op           string     `json:"op"`
	Arg1Value    *float64   `json:"arg1_value"`
	Arg1TaskID   *uuid.UUID `json:"arg1_task_id"`
	Arg2Value    *float64   `json:"arg2_value"`
	Arg2TaskID   *uuid.UUID `json:"arg2_task_id"`
	UnmetDeps    int32      `json:"unmet_deps"`
	Status       TaskStatus `json:"status"`
	IsRoot       bool       `json:"is_root"`
}

func (q *Queries) InsertTask(ctx context.Context, arg InsertTaskParams) error {
	_, err := q.db.Exec(ctx, insertTask,
		arg.ID,
		arg.ExpressionID,
		arg.Op,
		arg.Arg1Value,
		arg.Arg1TaskID,
		arg.Arg2Value,
		arg.Arg2TaskID,
		arg.UnmetDeps,
		arg.Status,
		arg.IsRoot,
	)
	return err
}

const markTaskReady = `-- name: MarkTaskReady :exec
UPDATE tasks SET status = 'ready', queued_at = now()
WHERE id = $1 AND status = 'pending'
`

func (q *Queries) MarkTaskReady(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markTaskReady, id)
	return err
}

const markTaskRunning = `-- name: MarkTaskRunning :exec
UPDATE tasks
SET status = 'running', worker_id = $2, attempt = $3, started_at = now()
WHERE id = $1 AND status IN ('ready', 'running')
`

type MarkTaskRunningParams struct {
	ID       uuid.UUID `json:"id"`
	WorkerID string    `json:"worker_id"`
	Attempt  int32     `json:"attempt"`
}

func (q *Queries) MarkTaskRunning(ctx context.Context, arg MarkTaskRunningParams) error {
	_, err := q.db.Exec(ctx, markTaskRunning, arg.ID, arg.WorkerID, arg.Attempt)
	return err
}
