// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package sqlcgen

import (
	"context"
)

// iteratorForInsertAuditEvents implements pgx.CopyFromSource.
type iteratorForInsertAuditEvents struct {
	rows                 []InsertAuditEventsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertAuditEvents) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertAuditEvents) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].OccurredAt,
		r.rows[0].EventType,
		r.rows[0].Service,
		r.rows[0].EntityType,
		r.rows[0].EntityID,
		r.rows[0].TraceID,
		r.rows[0].Actor,
		r.rows[0].Payload,
	}, nil
}

func (r iteratorForInsertAuditEvents) Err() error {
	return nil
}

func (q *Queries) InsertAuditEvents(ctx context.Context, arg []InsertAuditEventsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"audit_events"}, []string{"id", "occurred_at", "event_type", "service", "entity_type", "entity_id", "trace_id", "actor", "payload"}, &iteratorForInsertAuditEvents{rows: arg})
}
