// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
)

type AuditEvent struct {
	ID         uuid.UUID `json:"id"`
	OccurredAt time.Time `json:"occurred_at"`
	EventType  string    `json:"event_type"`
	Service    string    `json:"service"`
	EntityType string    `json:"entity_type"`
	EntityID   string    `json:"entity_id"`
	TraceID    string    `json:"trace_id"`
	Actor      string    `json:"actor"`
	Payload    []byte    `json:"payload"`
}
