// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const auditIngestLastMinute = `-- name: AuditIngestLastMinute :one
SELECT count(*) FROM audit_events WHERE occurred_at > now() - interval '1 minute'
`

func (q *Queries) AuditIngestLastMinute(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, auditIngestLastMinute)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const auditStatsByType = `-- name: AuditStatsByType :many
SELECT event_type, count(*) AS n
FROM audit_events
GROUP BY event_type
ORDER BY n DESC
`

type AuditStatsByTypeRow struct {
	EventType string `json:"event_type"`
	N         int64  `json:"n"`
}

func (q *Queries) AuditStatsByType(ctx context.Context) ([]AuditStatsByTypeRow, error) {
	rows, err := q.db.Query(ctx, auditStatsByType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditStatsByTypeRow
	for rows.Next() {
		var i AuditStatsByTypeRow
		if err := rows.Scan(&i.EventType, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAuditEvents = `-- name: CountAuditEvents :one
SELECT count(*) FROM audit_events
`

func (q *Queries) CountAuditEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

type InsertAuditEventsParams struct {
	ID         uuid.UUID `json:"id"`
	OccurredAt time.Time `json:"occurred_at"`
	EventType  string    `json:"event_type"`
	Service    string    `json:"service"`
	EntityType string    `json:"entity_type"`
	EntityID   string    `json:"entity_id"`
	TraceID    string    `json:"trace_id"`
	Actor      string    `json:"actor"`
	Payload    []byte    `json:"payload"`
}

const insertAuditEventsIdempotent = `-- name: InsertAuditEventsIdempotent :execrows
INSERT INTO audit_events (
    id, occurred_at, event_type, service,
    entity_type, entity_id, trace_id, actor, payload
)
SELECT unnest($1::uuid[]), unnest($2::timestamptz[]), unnest($3::text[]),
       unnest($4::text[]), unnest($5::text[]), unnest($6::text[]),
       unnest($7::text[]), unnest($8::text[]), unnest($9::jsonb[])
ON CONFLICT DO NOTHING
`

type InsertAuditEventsIdempotentParams struct {
	Column1 []uuid.UUID `json:"column_1"`
	Column2 []time.Time `json:"column_2"`
	Column3 []string    `json:"column_3"`
	Column4 []string    `json:"column_4"`
	Column5 []string    `json:"column_5"`
	Column6 []string    `json:"column_6"`
	Column7 []string    `json:"column_7"`
	Column8 []string    `json:"column_8"`
	Column9 [][]byte    `json:"column_9"`
}

// unnest-based multi-row insert with conflict skip: near-COPY throughput AND
// exactly-once effect under at-least-once delivery (retried batches no-op).
func (q *Queries) InsertAuditEventsIdempotent(ctx context.Context, arg InsertAuditEventsIdempotentParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertAuditEventsIdempotent,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Column9,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const queryAuditEvents = `-- name: QueryAuditEvents :many
SELECT id, occurred_at, event_type, service, entity_type, entity_id, trace_id, actor, payload FROM audit_events
WHERE ($1::timestamptz IS NULL OR occurred_at >= $1)
  AND ($2::timestamptz   IS NULL OR occurred_at <  $2)
  AND ($3::text     IS NULL OR event_type  = $3)
  AND ($4::text    IS NULL OR entity_type = $4)
  AND ($5::text      IS NULL OR entity_id   = $5)
  AND ($6::text       IS NULL OR trace_id    = $6)
  AND ($7::timestamptz IS NULL
       OR (occurred_at, id) < ($7::timestamptz, $8::uuid))
ORDER BY occurred_at DESC, id DESC
LIMIT $9
`

type QueryAuditEventsParams struct {
	FromTs     *time.Time  `json:"from_ts"`
	ToTs       *time.Time  `json:"to_ts"`
	EventType  *string     `json:"event_type"`
	EntityType *string     `json:"entity_type"`
	EntityID   *string     `json:"entity_id"`
	TraceID    *string     `json:"trace_id"`
	CursorTs   *time.Time  `json:"cursor_ts"`
	CursorID   pgtype.UUID `json:"cursor_id"`
	PageSize   int32       `json:"page_size"`
}

// Keyset pagination over (occurred_at, id) DESC; every filter is optional.
func (q *Queries) QueryAuditEvents(ctx context.Context, arg QueryAuditEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, queryAuditEvents,
		arg.FromTs,
		arg.ToTs,
		arg.EventType,
		arg.EntityType,
		arg.EntityID,
		arg.TraceID,
		arg.CursorTs,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.EventType,
			&i.Service,
			&i.EntityType,
			&i.EntityID,
			&i.TraceID,
			&i.Actor,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
