// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: expressions.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const countExpressions = `-- name: CountExpressions :one
SELECT count(*) FROM expressions
`

func (q *Queries) CountExpressions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countExpressions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const expressionProgress = `-- name: ExpressionProgress :one
SELECT
    count(*)                                            AS total,
    count(*) FILTER (WHERE status = 'done')             AS done
FROM tasks WHERE expression_id = $1
`

type ExpressionProgressRow struct {
	Total int64 `json:"total"`
	Done  int64 `json:"done"`
}

func (q *Queries) ExpressionProgress(ctx context.Context, expressionID uuid.UUID) (ExpressionProgressRow, error) {
	row := q.db.QueryRow(ctx, expressionProgress, expressionID)
	var i ExpressionProgressRow
	err := row.Scan(&i.Total, &i.Done)
	return i, err
}

const finalizeExpressionDone = `-- name: FinalizeExpressionDone :exec
UPDATE expressions
SET status = 'done', result = $2, done_at = now()
WHERE id = $1 AND status IN ('pending', 'in_progress')
`

type FinalizeExpressionDoneParams struct {
	ID     uuid.UUID `json:"id"`
	Result *float64  `json:"result"`
}

func (q *Queries) FinalizeExpressionDone(ctx context.Context, arg FinalizeExpressionDoneParams) error {
	_, err := q.db.Exec(ctx, finalizeExpressionDone, arg.ID, arg.Result)
	return err
}

const finalizeExpressionFailed = `-- name: FinalizeExpressionFailed :exec
UPDATE expressions
SET status = 'failed', error = $2, done_at = now()
WHERE id = $1 AND status IN ('pending', 'in_progress')
`

type FinalizeExpressionFailedParams struct {
	ID    uuid.UUID `json:"id"`
	Error *string   `json:"error"`
}

func (q *Queries) FinalizeExpressionFailed(ctx context.Context, arg FinalizeExpressionFailedParams) error {
	_, err := q.db.Exec(ctx, finalizeExpressionFailed, arg.ID, arg.Error)
	return err
}

const getExpression = `-- name: GetExpression :one
SELECT id, raw, status, result, error, trace_id, created_at, done_at FROM expressions WHERE id = $1
`

func (q *Queries) GetExpression(ctx context.Context, id uuid.UUID) (Expression, error) {
	row := q.db.QueryRow(ctx, getExpression, id)
	var i Expression
	err := row.Scan(
		&i.ID,
		&i.Raw,
		&i.Status,
		&i.Result,
		&i.Error,
		&i.TraceID,
		&i.CreatedAt,
		&i.DoneAt,
	)
	return i, err
}

const insertExpression = `-- name: InsertExpression :one
INSERT INTO expressions (id, raw, status, trace_id)
VALUES ($1, $2, 'pending', $3)
RETURNING id, raw, status, result, error, trace_id, created_at, done_at
`

type InsertExpressionParams struct {
	ID      uuid.UUID `json:"id"`
	Raw     string    `json:"raw"`
	TraceID string    `json:"trace_id"`
}

func (q *Queries) InsertExpression(ctx context.Context, arg InsertExpressionParams) (Expression, error) {
	row := q.db.QueryRow(ctx, insertExpression, arg.ID, arg.Raw, arg.TraceID)
	var i Expression
	err := row.Scan(
		&i.ID,
		&i.Raw,
		&i.Status,
		&i.Result,
		&i.Error,
		&i.TraceID,
		&i.CreatedAt,
		&i.DoneAt,
	)
	return i, err
}

const listExpressions = `-- name: ListExpressions :many
SELECT id, raw, status, result, error, trace_id, created_at, done_at FROM expressions
ORDER BY created_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListExpressionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListExpressions(ctx context.Context, arg ListExpressionsParams) ([]Expression, error) {
	rows, err := q.db.Query(ctx, listExpressions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expression
	for rows.Next() {
		var i Expression
		if err := rows.Scan(
			&i.ID,
			&i.Raw,
			&i.Status,
			&i.Result,
			&i.Error,
			&i.TraceID,
			&i.CreatedAt,
			&i.DoneAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markExpressionInProgress = `-- name: MarkExpressionInProgress :exec
UPDATE expressions SET status = 'in_progress'
WHERE id = $1 AND status = 'pending'
`

func (q *Queries) MarkExpressionInProgress(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markExpressionInProgress, id)
	return err
}
