// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package sqlcgen

import (
	"context"
)

const insertOutbox = `-- name: InsertOutbox :exec
INSERT INTO outbox (kind, payload) VALUES ($1, $2)
`

type InsertOutboxParams struct {
	Kind    string `json:"kind"`
	Payload []byte `json:"payload"`
}

func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) error {
	_, err := q.db.Exec(ctx, insertOutbox, arg.Kind, arg.Payload)
	return err
}

const markOutboxPublished = `-- name: MarkOutboxPublished :exec
UPDATE outbox SET published_at = now() WHERE id = ANY($1::bigint[])
`

func (q *Queries) MarkOutboxPublished(ctx context.Context, dollar_1 []int64) error {
	_, err := q.db.Exec(ctx, markOutboxPublished, dollar_1)
	return err
}

const pruneOutbox = `-- name: PruneOutbox :execrows
DELETE FROM outbox
WHERE published_at IS NOT NULL AND published_at < now() - interval '1 hour'
`

func (q *Queries) PruneOutbox(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, pruneOutbox)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const selectOutboxBatch = `-- name: SelectOutboxBatch :many
SELECT id, kind, payload FROM outbox
WHERE published_at IS NULL
ORDER BY id
LIMIT $1
FOR UPDATE SKIP LOCKED
`

type SelectOutboxBatchRow struct {
	ID      int64  `json:"id"`
	Kind    string `json:"kind"`
	Payload []byte `json:"payload"`
}

// Claimed inside a transaction: SKIP LOCKED lets orchestrator replicas relay
// concurrently without contending on the same rows.
func (q *Queries) SelectOutboxBatch(ctx context.Context, limit int32) ([]SelectOutboxBatchRow, error) {
	rows, err := q.db.Query(ctx, selectOutboxBatch, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectOutboxBatchRow
	for rows.Next() {
		var i SelectOutboxBatchRow
		if err := rows.Scan(&i.ID, &i.Kind, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
